{% set name = "trame-client" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-client-{{ version }}.tar.gz
  sha256: 60df253adcf640df41e4e769cfe13f298f4a5b6883a604d603479c7bcd3da6cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - trame
    - trame_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-client/
  summary: Internal client of trame
  license: MIT
  license_file:
    - LICENSE
    - trame_client/LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
