{% set name = "trame-client" %}
{% set version = "2.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-client-{{ version }}.tar.gz
  sha256: cce0d6445faee0a126010097cccaa06784861c42ad29c0fc4ed87e08dfc9b527

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - trame
    - trame_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-client/
  summary: Internal client of trame
  license: MIT
  license_file:
    - LICENSE
    - trame_client/LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
